/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rockgame;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author gygshwr
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }
    String Command[] = {"ROCK","PAPER","SCISSORS"};
    String Player;
    String CPU;
    int playerScore = 0;
    int cPUScore = 0;
    
    Random Rand = new Random();
    
    
    void Judge(String Player, String CPU) {
        
        if(Player.equals("ROCK") && CPU.equals("ROCK")) {
            Result.setText("TIE");
        }
        else if(Player.equals("PAPER") && CPU.equals("PAPER")) {
            Result.setText("TIE");
        }
        else if(Player.equals("SCISSORS") && CPU.equals("SCISSORS")) {
            Result.setText("TIE");
        }
        else if(Player.equals("ROCK") && CPU.equals("SCISSORS")) {
            Result.setText("PLAYER");
            playerScore++;
            PlayerScore.setText(Integer.toString(playerScore));
            
            
        }
         else if(Player.equals("SCISSORS") && CPU.equals("PAPER")) {
            Result.setText("PLAYER");
            playerScore++;
            PlayerScore.setText(Integer.toString(playerScore));
            
            
        }
         else if(Player.equals("PAPER") && CPU.equals("ROCK")) {
            Result.setText("PLAYER");
            playerScore++;
            PlayerScore.setText(Integer.toString(playerScore));
            
            
        }
         else if(Player.equals("SCISSORS") && CPU.equals("ROCK")) {
            Result.setText("CPU");
            cPUScore++;
            CPUScore.setText(Integer.toString(cPUScore));
            
            
        }
          else if(Player.equals("PAPER") && CPU.equals("SCISSORS")) {
            Result.setText("CPU");
            cPUScore++;
            CPUScore.setText(Integer.toString(cPUScore));
            
            
        }
          else if(Player.equals("ROCK") && CPU.equals("PAPER")) {
            Result.setText("CPU");
            cPUScore++;
            CPUScore.setText(Integer.toString(cPUScore));
            
            
        }
        
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Scissors = new javax.swing.JLabel();
        Rock = new javax.swing.JLabel();
        Paper = new javax.swing.JLabel();
        CPUScore1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PlayerScore = new javax.swing.JLabel();
        CPUScore = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        PlayerDisp = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        CPUDisp = new javax.swing.JLabel();
        CPUDisp2 = new javax.swing.JLabel();
        CPUScore2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        Scissors.setBackground(new java.awt.Color(255, 255, 102));
        Scissors.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        Scissors.setForeground(new java.awt.Color(255, 204, 102));
        Scissors.setText("SCISSORS");
        Scissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScissorsMouseClicked(evt);
            }
        });

        Rock.setBackground(new java.awt.Color(204, 204, 204));
        Rock.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        Rock.setForeground(new java.awt.Color(102, 255, 102));
        Rock.setText("ROCK");
        Rock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RockMouseClicked(evt);
            }
        });

        Paper.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        Paper.setForeground(new java.awt.Color(255, 255, 255));
        Paper.setText("PAPER");
        Paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaperMouseClicked(evt);
            }
        });

        CPUScore1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        CPUScore1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPUScore1.setText("CONTROLS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPUScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Paper)
                    .addComponent(Rock)
                    .addComponent(Scissors))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(CPUScore1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Paper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scissors)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("PLAYER");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("CPU");

        PlayerScore.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        PlayerScore.setForeground(new java.awt.Color(102, 0, 102));
        PlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PlayerScore.setText("0");

        CPUScore.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        CPUScore.setForeground(new java.awt.Color(255, 0, 0));
        CPUScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPUScore.setText("0");

        Exit.setBackground(new java.awt.Color(255, 102, 102));
        Exit.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Exit.setText("EXIT");
        Exit.setBorder(null);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        PlayerDisp.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        PlayerDisp.setForeground(new java.awt.Color(102, 0, 102));
        PlayerDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PlayerDisp.setText("PLAY");

        Result.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        Result.setForeground(new java.awt.Color(102, 51, 255));
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setText("TIE");

        CPUDisp.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        CPUDisp.setForeground(new java.awt.Color(255, 0, 0));
        CPUDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPUDisp.setText("CPU");

        CPUDisp2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        CPUDisp2.setForeground(new java.awt.Color(255, 102, 102));
        CPUDisp2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPUDisp2.setText("VS");

        CPUScore2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        CPUScore2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("ROCK - PAPER - SCISSORS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CPUScore, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPUDisp2)
                                    .addComponent(CPUDisp)
                                    .addComponent(PlayerDisp))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(CPUScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerScore)
                    .addComponent(CPUScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Result)
                .addGap(18, 18, 18)
                .addComponent(CPUDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPUDisp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(CPUScore2)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RockMouseClicked
        // TODO add your handling code here:
        Player = Command[0];
        CPU = Command[Rand.nextInt(3)];
        
        PlayerDisp.setText(Player);
        CPUDisp.setText(CPU);
        
        Judge(Player,CPU);
        
    }//GEN-LAST:event_RockMouseClicked

    private void PaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaperMouseClicked
        // TODO add your handling code here:
        Player = Command[1];
        CPU = Command[Rand.nextInt(3)];
        
        PlayerDisp.setText(Player);
        CPUDisp.setText(CPU);
        Judge(Player,CPU);

        
        
    }//GEN-LAST:event_PaperMouseClicked

    private void ScissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScissorsMouseClicked
        // TODO add your handling code here:
        Player = Command[2];
        CPU = Command[Rand.nextInt(3)];
        
        PlayerDisp.setText(Player);
        CPUDisp.setText(CPU);
        Judge(Player,CPU);

    }//GEN-LAST:event_ScissorsMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        if(playerScore == cPUScore) {
            JOptionPane.showMessageDialog(this, "It's a Tie!","RESULT",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(playerScore > cPUScore) {
             JOptionPane.showMessageDialog(this, "You Won!","RESULT",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
                    JOptionPane.showMessageDialog(this, "Alas! You Lost","RESULT",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPUDisp;
    private javax.swing.JLabel CPUDisp2;
    private javax.swing.JLabel CPUScore;
    private javax.swing.JLabel CPUScore1;
    private javax.swing.JLabel CPUScore2;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Paper;
    private javax.swing.JLabel PlayerDisp;
    private javax.swing.JLabel PlayerScore;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel Rock;
    private javax.swing.JLabel Scissors;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
